### ISSUE TITLE
Illustrator CC 2014 compatibility (18.0)

### ISSUE THREAD

**Issue by mkj-is** [tomkrcha/drawscript#8]
> This extension can not be installed, it requires Illustrator version in range of inclusively between 16.0 and 17.9

Does the extension run in the new Illustrator? Current version is 18.0. Is there any incompatibility?

**Comment by aaronbuchanan** [comment]
Thanks for the update @MylesCaley — Can I ask which ZXPSignCmd flags you used?

I see a few options but I'm not familiar with the signing process:
```bash
Usage:
    ZXPSignCmd -sign <inputDirectory> <outputZxp> <p12> <p12Password> [options]
	options:
		-tsa <timestampURL> - will attempt to timestamp the ZXP using supplied timestamp server. For example, https://timestamp.geotrust.com/tsa

    ZXPSignCmd -sign <inputDirectory> <outputZxp> -s <identity> [options]
	options:
		-keychain <filename> - identity is only looked-for in the specific keychain given

		-tsa <timestampURL> - will attempt to timestamp the ZXP using supplied timestamp server. For example, https://timestamp.geotrust.com/tsa

    ZXPSignCmd -verify <zxp>|<extensionRootDirectory> [options]
	options:
		-certInfo - will print out information about certificates (including timestamp and certificate revocation information)
		-skipOnlineRevocationChecks - will skip online checks for certificate revocation (certificate revocation checks only happen with -certInfo flag set)
		-addCerts <certificate1> <certificate2>... - will verify certificate chain and assess whether or not DER encoded certificates passed in are included

    ZXPSignCmd -selfSignedCert <countryCode> <stateOrProvince> <organization> <commonName> <password> <outputPath.p12> [options]
	options: 
		-locality <locality> -orgUnit <orgUnit> -email <email> -validityDays <validityDays> - are optional attributes for self-signed p12 certificates
```

**Comment by aaronbuchanan** [comment]
Answering my own question here, just created a self signed cert with:
Thanks for the update @MylesCaley — Can I ask which ZXPSignCmd flags you used?

I see a few options but I'm not familiar with the signing process:
```bash
    ./ZXPSignCmd -selfSignedCert <countryCode> <stateOrProvince> <organization> <commonName> <password> <outputPath.p12>
```

Then used the same pass and p2 path in the following:
```bash
    ./ZXPSignCmd -sign <inputDirectory> <outputZxp> <p12> <p12Password>
```

**Comment by MylesCaley** [comment]
Sure, entire recipe... 
1. to unzip: 7za x -oextension -r  Drawscript.zxp
2. modify the file: vi extension/CSXS/manifest.xml
3. create a self signed cert to use for signing : ./ccextensionsmac/ZXPSignCmd -selfSignedCert US KY whatever whatever password path.p12
4. ./ccextensionsmac/ZXPSignCmd -sign extension mine3.zxp path.p12 password

**Comment by alwaysbrightblue** [comment]
@MylesCaley it looks like 7zip is Windows only.  Is there a way to do this on a Mac?

**Comment by MylesCaley** [comment]
@alwaysbrightblue Yes, I use mac ports (https://www.macports.org/). I am sure there are other solutions as well. Once you have mac ports running and updated on your system you can install new packages:

sudo port install p7zip 

then to extract the archive:

7za x -oextension -r  Drawscript.zxp

**Comment by alwaysbrightblue** [comment]
@MylesCaley I got it!  Took me a bit, but your instructions worked.

The only thing I would recommend to other "n00bs" is when you modify the manifest.xml in Step 2, use Sublime Text 2 or whatever text editor, line 12 change the Version to read <code>"18.1.1"</code> and remove the other numbers in there.  I was not getting this to display because I was trying to just add 18.1.1 to the array (I think it was an array?), but when I removed 16.0 and 17.0 it worked for me.  Save that file, then proceed with Step 3 and 4. 

And, if you're getting "not found" errors, make sure you cd into the correct directory.  I placed everything on my Desktop to do the extractions and this process.  Move the new .zxp to another folder that you'll keep your scripts in and then install to Illustrator using Extension Manager.

Thanks again everyone.  Much appreciated.

**Comment by alwaysbrightblue** [comment]
A reference for how manifests should look is helpful, too:

https://www.adobeexchange.com/resources/7

**Comment by roddyguy22** [comment]
anyone know where to simply download a new version that's compatible? I gave this a quick re-assigning, but must be doing something wrong and don't want to spend hours going down the rabbit hole.

**Comment by ttessman** [comment]
@MylesCaley @CodeAngry - big thank you

**Comment by eshkermene** [comment]
Help run his version of CC 19.1.0 (2015)

**Comment by vennsoh** [comment]
Can someone post a download link that support up to Adobe Illustrator CC 2015?

**Comment by rock7-dan** [comment]
Updated installations details for Illustrator CC 2015...

Download and decompress Drawscript.zxp (as per @MylesCaley) - open up CSXS/manifest.xml and modify the ExecutionEnvironment element as below:

```
  <ExecutionEnvironment>
  <HostList>
    <Host Name="ILST" Version="17.0" />
  </HostList>
  <LocaleList>
    <Locale Code="All" />
  </LocaleList>
  <RequiredRuntimeList>
    <RequiredRuntime Name="CSXS" Version="4.2" />
    </RequiredRuntimeList>
  </ExecutionEnvironment>
```

Rename the "extension" folder to "com.example.Drawscript" and move the folder into your extensions folder: (Mac OSX: /Library/Application Support/Adobe/CEP/extensions).

Restart Illustrator and away you go!

**Comment by eramdam** [comment]
@rock7-dan I followed your instructions for Illustrator CC 2015 (19.0) and I can indeed see the extensions under the Window > Extensions menu but when I click on it, nothing happens. Do you think there is a solution?

**Comment by FlorianLudwig** [comment]
We done a rudimentary version of drawscript ourselves and open sourced it https://github.com/GreyRook/Draw2Script - it fits just what we needed from drawscript but really nothing else.  It is working on a current Illustrator CC and is open source!

If you try it let us know if it was useful for you or what it is missing to be useful for you.

**Comment by mkj-is** [comment]
As it stands now there are many apps that can convert paths into various programming language code. This project is no longer mantained. I am just going through my old open issue and closing them if they are not relevant anymore.
